ProyectoFinal/Controllers/UploadPhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class UploadPhotosController : Controller
    {
        private PatientModelDBContext db = new PatientModelDBContext();

        //
        // GET: /UploadPhotos/

        public ActionResult Index()
        {
            var uploadimagen = db.UploadImagen.Include(i => i.PatientModel);
            return View(uploadimagen.ToList());
        }

        //
        // GET: /UploadPhotos/Details/5

        public ActionResult Details(int id = 0)
        {
            Image image = db.UploadImagen.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        //
        // GET: /UploadPhotos/Create

        public ActionResult Create()
        {
            ViewBag.PatientModelId = new SelectList(db.Patients, "Id", "Nombre");
            return View();
        }

        //
        // POST: /UploadPhotos/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Image imagen, HttpPostedFileBase file, int id = 0)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/") + file.FileName);
                    imagen.ImagePath = file.FileName;
                }
                imagen.CreadoPor = User.Identity.Name;
                imagen.PatientModelId = id;
                db.UploadImagen.Add(imagen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PatientModelId = new SelectList(db.Patients, "Id", "Nombre", imagen.PatientModelId);
            return View(imagen);
        }

        //
        // GET: /UploadPhotos/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Image image = db.UploadImagen.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientModelId = new SelectList(db.Patients, "Id", "Nombre", image.PatientModelId);
            return View(image);
        }

        //
        // POST: /UploadPhotos/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Image image)
        {
            if (ModelState.IsValid)
            {
                db.Entry(image).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PatientModelId = new SelectList(db.Patients, "Id", "Nombre", image.PatientModelId);
            return View(image);
        }

        //
        // GET: /UploadPhotos/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Image image = db.UploadImagen.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        //
        // POST: /UploadPhotos/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Image image = db.UploadImagen.Find(id);
            db.UploadImagen.Remove(image);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Views/UploadPhotos/Create.cshtml
@model ProyectoFinal.Models.Image

@{
    ViewBag.Title = "Create";
}

<h2>Agregar Imagen</h2>

@using (Html.BeginForm("Create", "UploadPhotos", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Image</legend>

        @Html.HiddenFor(model => model.CreadoPor)

        <div class="editor-label">
            @*@Html.LabelFor(model => model.ImagePath)*@
        </div>
        <div class="editor-field">
            <form action="~/UploadPhotos/Create" method="post">
            <input id="ImagePath" title="Elija un archivo" type="file" name="file" />
                <p><input type="submit" value="Create" /></p>
                </form>
        </div>
        

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoFinal/Views/UploadPhotos/Delete.cshtml
@model ProyectoFinal.Models.Image

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Image</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ImagePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImagePath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreadoPor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreadoPor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PatientModel.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PatientModel.Nombre)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ProyectoFinal/Views/UploadPhotos/Details.cshtml
@model ProyectoFinal.Models.Image

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Image</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ImagePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImagePath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreadoPor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreadoPor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PatientModel.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PatientModel.Nombre)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoFinal/Views/UploadPhotos/Edit.cshtml
@model ProyectoFinal.Models.Image

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Image</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.ImagePath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImagePath)
            @Html.ValidationMessageFor(model => model.ImagePath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreadoPor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreadoPor)
            @Html.ValidationMessageFor(model => model.CreadoPor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PatientModelId, "PatientModel")
        </div>
        <div class="editor-field">
            @Html.DropDownList("PatientModelId", String.Empty)
            @Html.ValidationMessageFor(model => model.PatientModelId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoFinal/Views/UploadPhotos/Index.cshtml
@model IEnumerable<ProyectoFinal.Models.Image>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
@*            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Ajax.ActionLink("Delete", "Delete", new {id = item.ID} })*@
        </td>
    </tr>
}

</table>