ProyectoFinal/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private PatientModelDBContext db = new PatientModelDBContext();

        //
        // GET: /Patients/

        public ActionResult Index()
        {
            return View(db.Patients.ToList());
        }

        //
        // GET: /Patients/Details/5

        public ActionResult Details(int id = 0)
        {
            PatientModel patientmodel = db.Patients.Find(id);
            if (patientmodel == null)
            {
                return HttpNotFound();
            }
            var rootObjects = db.RootObjects.Where(o => o.modeloDatos.Cedula == patientmodel.Cedula).OrderBy(o => o.id).ToList();
            ViewBag.rootObjects = rootObjects;
            return View(new PatientDetailsVM
            {
                rootObject = rootObjects,
                patient = patientmodel
            });
        }

        //
        // GET: /Patients/Create

        public ActionResult Create()
        {
            // DropDown Tipos de Sangre-----------------------------------
            List<SelectListItem> blood = new List<SelectListItem>();
            blood.Add(new SelectListItem { Text = "", Value = "" });
            blood.Add(new SelectListItem { Text = "O+", Value = "O+" });
            blood.Add(new SelectListItem { Text = "O-", Value = "O-" });
            blood.Add(new SelectListItem { Text = "A+", Value = "A+" });
            blood.Add(new SelectListItem { Text = "A-", Value = "A-" });
            blood.Add(new SelectListItem { Text = "B+", Value = "B+" });
            blood.Add(new SelectListItem { Text = "B-", Value = "B-" });
            blood.Add(new SelectListItem { Text = "AB+", Value = "AB+" });
            blood.Add(new SelectListItem { Text = "AB-", Value = "AB-" });
            ViewBag.sangre = blood;
            //------------------------------------------------------------
            // DropDown Sexo-----------------------------------
            List<SelectListItem> sex = new List<SelectListItem>();
            sex.Add(new SelectListItem { Text = "", Value = "" });
            sex.Add(new SelectListItem { Text = "Femenino", Value = "Femenino" });
            sex.Add(new SelectListItem { Text = "Masculino", Value = "Masculino" });
            ViewBag.sexo = sex;
            //------------------------------------------------------------
            //DropDown Seguros--------------------------------------------
            List<SelectListItem> insurance = new List<SelectListItem>();
            insurance.Add(new SelectListItem { Text = "", Value = "" });
            insurance.Add(new SelectListItem { Text = "Ninguno", Value = "Ninguno" });
            insurance.Add(new SelectListItem { Text = "ARS Humano", Value = "Humano" });
            insurance.Add(new SelectListItem { Text = "La Colonial", Value = "La Colonial" });
            insurance.Add(new SelectListItem { Text = "Mapfre BHD", Value = "Mapfre" });
            insurance.Add(new SelectListItem { Text = "ARS Palic", Value = "Palic" });
            insurance.Add(new SelectListItem { Text = "ARS Senasa", Value = "Senasa" });
            insurance.Add(new SelectListItem { Text = "Seguros Universal", Value = "Universal" });
            ViewBag.seguro = insurance;
            //------------------------------------------------------------

            return View();
        }

        //
        // POST: /Patients/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientModel patientmodel)
        {
            if (!ModelState.IsValid)
            {
                patientmodel.CreadoPor = User.Identity.Name;
                db.Patients.Add(patientmodel);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = patientmodel.Id });
            }
            return View(patientmodel);
        }

        //
        // GET: /Patients/Edit/5


        public ActionResult Edit(int id = 0)
        {
            // DropDown Tipos de Sangre-----------------------------------
            List<SelectListItem> blood = new List<SelectListItem>();
            blood.Add(new SelectListItem { Text = "", Value = "" });
            blood.Add(new SelectListItem { Text = "O+", Value = "O+" });
            blood.Add(new SelectListItem { Text = "O-", Value = "O-" });
            blood.Add(new SelectListItem { Text = "A+", Value = "A+" });
            blood.Add(new SelectListItem { Text = "A-", Value = "A-" });
            blood.Add(new SelectListItem { Text = "B+", Value = "B+" });
            blood.Add(new SelectListItem { Text = "B-", Value = "B-" });
            blood.Add(new SelectListItem { Text = "AB+", Value = "AB+" });
            blood.Add(new SelectListItem { Text = "AB-", Value = "AB-" });
            ViewBag.sangre = blood;
            //------------------------------------------------------------
            // DropDown Sexo-----------------------------------
            List<SelectListItem> sex = new List<SelectListItem>();
            sex.Add(new SelectListItem { Text = "", Value = "" });
            sex.Add(new SelectListItem { Text = "Femenino", Value = "Femenino" });
            sex.Add(new SelectListItem { Text = "Masculino", Value = "Masculino" });
            ViewBag.sexo = sex;
            //------------------------------------------------------------
            //DropDown Seguros--------------------------------------------
            List<SelectListItem> insurance = new List<SelectListItem>();
            insurance.Add(new SelectListItem { Text = "", Value = "" });
            insurance.Add(new SelectListItem { Text = "Ninguno", Value = "Ninguno" });
            insurance.Add(new SelectListItem { Text = "ARS Humano", Value = "ARS Humano" });
            insurance.Add(new SelectListItem { Text = "La Colonial", Value = "La Colonial" });
            insurance.Add(new SelectListItem { Text = "Mapfre BHD", Value = "Mapfre BHD" });
            insurance.Add(new SelectListItem { Text = "ARS Palic", Value = "ARS Palic" });
            insurance.Add(new SelectListItem { Text = "ARS Senasa", Value = "ARS Senasa" });
            insurance.Add(new SelectListItem { Text = "Seguros Universal", Value = "Seguros Universal" });
            ViewBag.seguro = insurance;
            //------------------------------------------------------------

            PatientModel patientmodel = db.Patients.Find(id);
            if (patientmodel == null)
            {
                return HttpNotFound();
            }
            return View(patientmodel);
        }

        //
        // POST: /Patients/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PatientModel patientmodel)
        {
            if (ModelState.IsValid)
            {
                patientmodel.CreadoPor = User.Identity.Name;
                db.Entry(patientmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = patientmodel.Id });
            }
            return View(patientmodel);
        }

        //
        // GET: /Patients/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PatientModel patientmodel = db.Patients.Find(id);
            if (patientmodel == null)
            {
                return HttpNotFound();
            }
            return View(patientmodel);
        }

        //
        // POST: /Patients/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PatientModel patientmodel = db.Patients.Find(id);
            db.Patients.Remove(patientmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        //Search Box
        public ActionResult SearchPatients(string searchString)
        {
            ViewBag.isSearch = searchString;
            var patients = from m in db.Patients        
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                patients = patients.Where(s =>
                    s.Nombre.Contains(searchString) ||
                    s.Apellido.Contains(searchString) ||
                    s.NumeroSeguroMedico.Contains(searchString) ||
                    (s.Nombre + " " + s.Apellido).Contains(searchString));
            }
            else
            {
                patients = new List<PatientModel>().AsQueryable();
            }

            return View(patients);
        }

        //Formulario de Presion sanguinea
        public ActionResult FormPresionSanguinea(int id)
        {
            var vm = db.FormBlood.Where(l => l.PatientModelId == id).AsEnumerable();
            return View(vm);
        }

        //Formulario de Signos Vitales
        public ActionResult FormSignosVitales(int id)
        {
            var sv = db.FormVital.Where(v => v.PatientModelId == id).AsEnumerable();
            return View(sv);
        }

        //Formulario de Vacunas
        public ActionResult FormVacunas(int id)
        {
            var va = db.FormVacci.Where(n => n.PatientModelId == id).AsEnumerable();
            return View(va);
        }

        public ActionResult Upload(int id)
        {
            var ph = db.UploadImagen.Where(p => p.PatientModelId == id).AsEnumerable();
            return View(ph);
        }

    }

    public class PatientDetailsVM 
    {

ProyectoFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Sistema Medico Integrado</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        @if (Request.IsAuthenticated){
        <header>
                <section id="cabecera">
            <div class="content-wrapper">
                <div class="float-left">                    
                    <p class="site-title">
                        <a href="~/Home/Index"> <img src="~/Images/logo.png" width="151" height="47" style="position:absolute;top:0px;left:20px" /> </a>
                        @*@Html.ActionLink("SMI", "Index", "Home", null, new { style="color:#007ACD;font-weight:900;font-family:'SketchFlow Print';font-size:45px;position:absolute;top:0px;left:20px" })*@
@*                        <img src="~/Images/logo.png" width="22" height="22" style="" />
                        <img src="~/Images/virus.png" width="22" height="22" />
                        <img src="~/Images/blood pressure.png" width="22" height="22" />
                        <img src="~/Images/iv bag.png" width="22" height="22" />
                        <img src="~/Images/bone.png" width="22" height="22" />
                        <img src="~/Images/surgeon.png" width="22" height="22" />
                        <img src="~/Images/ambulance car.png" width="22" height="22" />*@
                    </p>
                    <div class="left rounded" style="position:absolute;top:10%;left:30%;clear:both">
    <form action="~/Patients/SearchPatients" method="post">
    <input type="text" name="searchString" class="search left rounded" placeholder="Buscar paciente por nombre, apellido..." />
    <input type="submit" value="Buscar" style="height:28px; border-top-right-radius:4px;border-bottom-right-radius:4px;
    border-bottom-left-radius:0px;border-top-left-radius:0px;border-color:#ccc;background-color:#F8F8F8; color:black;font-weight:700" />
        </form>
</div>
                </div>
                <div>
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                </div>
                    <nav>
                        <ul id="menu">
                            <li>
                                @Html.ActionLink("Sala de Emergencias", "EmergencyRoom", "Home")
                                @*@Html.ActionLink("Buscar Pacientes", "SearchPatients", "Patients")*@
                                @Html.ActionLink("Crear Paciente", "Create", "Patients")
@*                                <form action="~/Home/EmergencyRoom" method="post">
                                <input type="submit" value="Sala de Emergencias" style="width:150px;height:30px;background-image:url(/Images/button.jpg);border-width:0px;font-weight:900">
                                    </form>
                                <form action="~/Patients/SearchPatients" method="post">
                                <input type="submit" value="Buscar Pacientes" style="width:150px;height:30px;background-image:url(/Images/button.jpg);border-width:0px;font-weight:900">                                
                                    </form>
                                <form action="~/Patients/Create" method="post">
                                <input type="submit" value="Crear Paciente" style="width:150px;height:30px;background-image:url(/Images/button.jpg);border-width:0px;font-weight:900">
                                    </form>*@
                            </li>
                        </ul>
                    </nav> 
            </div>
                </section>
        </header>
        }
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()                                 
            </section>
        </div>
@*        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Sistema Medico Integrado</p>
                </div>
            </div>
        </footer>*@

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>