ProyectoFinal/Controllers/FormBloodController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    [Authorize]
    public class FormBloodController : Controller
    {
        private PatientModelDBContext db = new PatientModelDBContext();

        //
        // GET: /FormBlood/

        public ActionResult Index()
        {
            return View(db.FormBlood.ToList());
        }

        //
        // GET: /FormBlood/Details/5

        public ActionResult Details(int id = 0)
        {
            FormBloodPressure formbloodpressure = db.FormBlood.Find(id);
            if (formbloodpressure == null)
            {
                return HttpNotFound();
            }
            return View(formbloodpressure);
        }

        //
        // GET: /FormBlood/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /FormBlood/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormBloodPressure formbloodpressure, int id = 0)
        {
            if (!ModelState.IsValid)
            {
                formbloodpressure.CreadoPor = User.Identity.Name;
                formbloodpressure.PatientModelId = id;
                db.FormBlood.Add(formbloodpressure);
                db.SaveChanges();
                return RedirectToAction("Index", "Patients", new {id = id});
            }

            return View(formbloodpressure);
        }

        //
        // GET: /FormBlood/Edit/5

        public ActionResult Edit(int id = 0)
        {
            FormBloodPressure formbloodpressure = db.FormBlood.Find(id);
            if (formbloodpressure == null)
            {
                return HttpNotFound();
            }
            return View(formbloodpressure);            
        }

        //
        // POST: /FormBlood/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormBloodPressure formbloodpressure)
        {
            if (!ModelState.IsValid)
            {
                formbloodpressure.CreadoPor = User.Identity.Name;
                db.Entry(formbloodpressure).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(formbloodpressure);
        }

        //
        // GET: /FormBlood/Delete/5

        public ActionResult Delete(int id = 0)
        {
            FormBloodPressure formbloodpressure = db.FormBlood.Find(id);
            if (formbloodpressure == null)
            {
                return HttpNotFound();
            }
            return View(formbloodpressure);
        }

        //
        // POST: /FormBlood/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FormBloodPressure formbloodpressure = db.FormBlood.Find(id);
            db.FormBlood.Remove(formbloodpressure);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private PatientModelDBContext db = new PatientModelDBContext();

        //
        // GET: /Patients/

        public ActionResult Index()
        {
            return View(db.Patients.ToList());
        }

        //
        // GET: /Patients/Details/5

        public ActionResult Details(int id = 0)
        {
            PatientModel patientmodel = db.Patients.Find(id);
            if (patientmodel == null)
            {
                return HttpNotFound();
            }
            var rootObjects = db.RootObjects.Where(o => o.modeloDatos.Cedula == patientmodel.Cedula).OrderBy(o => o.id).ToList();
            ViewBag.rootObjects = rootObjects;
            return View(new PatientDetailsVM
            {
                rootObject = rootObjects,
                patient = patientmodel
            });
        }

        //
        // GET: /Patients/Create

        public ActionResult Create()
        {
            // DropDown Tipos de Sangre-----------------------------------
            List<SelectListItem> blood = new List<SelectListItem>();
            blood.Add(new SelectListItem { Text = "", Value = "" });
            blood.Add(new SelectListItem { Text = "O+", Value = "O+" });
            blood.Add(new SelectListItem { Text = "O-", Value = "O-" });
            blood.Add(new SelectListItem { Text = "A+", Value = "A+" });
            blood.Add(new SelectListItem { Text = "A-", Value = "A-" });
            blood.Add(new SelectListItem { Text = "B+", Value = "B+" });
            blood.Add(new SelectListItem { Text = "B-", Value = "B-" });
            blood.Add(new SelectListItem { Text = "AB+", Value = "AB+" });
            blood.Add(new SelectListItem { Text = "AB-", Value = "AB-" });
            ViewBag.sangre = blood;
            //------------------------------------------------------------
            // DropDown Sexo-----------------------------------
            List<SelectListItem> sex = new List<SelectListItem>();
            sex.Add(new SelectListItem { Text = "", Value = "" });
            sex.Add(new SelectListItem { Text = "Femenino", Value = "Femenino" });
            sex.Add(new SelectListItem { Text = "Masculino", Value = "Masculino" });
            ViewBag.sexo = sex;
            //------------------------------------------------------------
            //DropDown Seguros--------------------------------------------
            List<SelectListItem> insurance = new List<SelectListItem>();
            insurance.Add(new SelectListItem { Text = "", Value = "" });
            insurance.Add(new SelectListItem { Text = "Ninguno", Value = "Ninguno" });
            insurance.Add(new SelectListItem { Text = "ARS Humano", Value = "Humano" });
            insurance.Add(new SelectListItem { Text = "La Colonial", Value = "La Colonial" });
            insurance.Add(new SelectListItem { Text = "Mapfre BHD", Value = "Mapfre" });
            insurance.Add(new SelectListItem { Text = "ARS Palic", Value = "Palic" });
            insurance.Add(new SelectListItem { Text = "ARS Senasa", Value = "Senasa" });
            insurance.Add(new SelectListItem { Text = "Seguros Universal", Value = "Universal" });
            ViewBag.seguro = insurance;
            //------------------------------------------------------------

            return View();
        }

        //
        // POST: /Patients/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientModel patientmodel)
        {
            if (!ModelState.IsValid)
            {
                patientmodel.CreadoPor = User.Identity.Name;
                db.Patients.Add(patientmodel);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = patientmodel.Id });
            }
            return View(patientmodel);
        }

        //
        // GET: /Patients/Edit/5


        public ActionResult Edit(int id = 0)
        {
            // DropDown Tipos de Sangre-----------------------------------
            List<SelectListItem> blood = new List<SelectListItem>();
            blood.Add(new SelectListItem { Text = "", Value = "" });
            blood.Add(new SelectListItem { Text = "O+", Value = "O+" });
            blood.Add(new SelectListItem { Text = "O-", Value = "O-" });
            blood.Add(new SelectListItem { Text = "A+", Value = "A+" });
            blood.Add(new SelectListItem { Text = "A-", Value = "A-" });
            blood.Add(new SelectListItem { Text = "B+", Value = "B+" });
            blood.Add(new SelectListItem { Text = "B-", Value = "B-" });
            blood.Add(new SelectListItem { Text = "AB+", Value = "AB+" });
            blood.Add(new SelectListItem { Text = "AB-", Value = "AB-" });
            ViewBag.sangre = blood;
            //------------------------------------------------------------
            // DropDown Sexo-----------------------------------
            List<SelectListItem> sex = new List<SelectListItem>();
            sex.Add(new SelectListItem { Text = "", Value = "" });
            sex.Add(new SelectListItem { Text = "Femenino", Value = "Femenino" });
            sex.Add(new SelectListItem { Text = "Masculino", Value = "Masculino" });
            ViewBag.sexo = sex;
            //------------------------------------------------------------
            //DropDown Seguros--------------------------------------------
            List<SelectListItem> insurance = new List<SelectListItem>();
            insurance.Add(new SelectListItem { Text = "", Value = "" });
            insurance.Add(new SelectListItem { Text = "Ninguno", Value = "Ninguno" });
            insurance.Add(new SelectListItem { Text = "ARS Humano", Value = "ARS Humano" });
            insurance.Add(new SelectListItem { Text = "La Colonial", Value = "La Colonial" });
            insurance.Add(new SelectListItem { Text = "Mapfre BHD", Value = "Mapfre BHD" });
            insurance.Add(new SelectListItem { Text = "ARS Palic", Value = "ARS Palic" });
            insurance.Add(new SelectListItem { Text = "ARS Senasa", Value = "ARS Senasa" });
            insurance.Add(new SelectListItem { Text = "Seguros Universal", Value = "Seguros Universal" });
            ViewBag.seguro = insurance;
            //------------------------------------------------------------

            PatientModel patientmodel = db.Patients.Find(id);
            if (patientmodel == null)
            {
                return HttpNotFound();
            }
            return View(patientmodel);
        }

        //
        // POST: /Patients/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PatientModel patientmodel)
        {
            if (ModelState.IsValid)
            {
                patientmodel.CreadoPor = User.Identity.Name;
                db.Entry(patientmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = patientmodel.Id });
            }
            return View(patientmodel);
        }

        //
        // GET: /Patients/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PatientModel patientmodel = db.Patients.Find(id);
            if (patientmodel == null)
            {
                return HttpNotFound();
            }
            return View(patientmodel);
        }

        //
        // POST: /Patients/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PatientModel patientmodel = db.Patients.Find(id);
            db.Patients.Remove(patientmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        //Search Box
        public ActionResult SearchPatients(string searchString)
        {
            ViewBag.isSearch = searchString;
            var patients = from m in db.Patients        
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                patients = patients.Where(s =>
                    s.Nombre.Contains(searchString) ||
                    s.Apellido.Contains(searchString) ||
                    s.NumeroSeguroMedico.Contains(searchString) ||
                    (s.Nombre + " " + s.Apellido).Contains(searchString));
            }
            else
            {
                patients = new List<PatientModel>().AsQueryable();
            }

            return View(patients);
        }

        //Formulario de Presion sanguinea
        public ActionResult FormPresionSanguinea(int id)
        {
            var vm = db.FormBlood.Where(l => l.PatientModelId == id).AsEnumerable();
            return View(vm);
        }

        //Formulario de Signos Vitales
        public ActionResult FormSignosVitales(int id)
        {
            var sv = db.FormVital.Where(v => v.PatientModelId == id).AsEnumerable();
            return View(sv);
        }

        //Formulario de Vacunas
        public ActionResult FormVacunas(int id)
        {
            var va = db.FormVacci.Where(n => n.PatientModelId == id).AsEnumerable();
            return View(va);
        }

        public ActionResult Upload(int id)
        {
            var ph = db.UploadImagen.Where(p => p.PatientModelId == id).AsEnumerable();
            return View(ph);
        }

    }

    public class PatientDetailsVM 
    {

ProyectoFinal/Controllers/VitalSignController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    [Authorize]
    public class VitalSignController : Controller
    {
        private PatientModelDBContext db = new PatientModelDBContext();

        //
        // GET: /VitalSign/

        public ActionResult Index()
        {
            return View(db.FormVital.ToList());
        }

        //
        // GET: /VitalSign/Details/5

        public ActionResult Details(int id = 0)
        {
            FormVitalSigns formvitalsigns = db.FormVital.Find(id);
            if (formvitalsigns == null)
            {
                return HttpNotFound();
            }
            return View(formvitalsigns);
        }

        //
        // GET: /VitalSign/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /VitalSign/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormVitalSigns formvitalsigns, int id = 0)
        {
            if (!ModelState.IsValid)
            {
                formvitalsigns.CreadoPor = User.Identity.Name;
                formvitalsigns.PatientModelId = id;
                db.FormVital.Add(formvitalsigns);
                db.SaveChanges();
                return RedirectToAction("Index", "Patients", new { id = id });
            }

            return View(formvitalsigns);
        }

        //
        // GET: /VitalSign/Edit/5

        public ActionResult Edit(int id = 0)
        {
            FormVitalSigns formvitalsigns = db.FormVital.Find(id);
            if (formvitalsigns == null)
            {
                return HttpNotFound();
            }
            return View(formvitalsigns);
        }

        //
        // POST: /VitalSign/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormVitalSigns formvitalsigns)
        {
            if (!ModelState.IsValid)
            {
                formvitalsigns.CreadoPor = User.Identity.Name;
                db.Entry(formvitalsigns).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(formvitalsigns);
        }

        //
        // GET: /VitalSign/Delete/5

        public ActionResult Delete(int id = 0)
        {
            FormVitalSigns formvitalsigns = db.FormVital.Find(id);
            if (formvitalsigns == null)
            {
                return HttpNotFound();
            }
            return View(formvitalsigns);
        }

        //
        // POST: /VitalSign/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FormVitalSigns formvitalsigns = db.FormVital.Find(id);
            db.FormVital.Remove(formvitalsigns);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Views/Patients/Details.cshtml
@using ProyectoFinal.Models
@model ProyectoFinal.Controllers.PatientDetailsVM

@{
    ViewBag.Title = "Perfil del paciente";
}
<!DOCTYPE html>
<meta name="viewport" content="width=device-width" />
<div>
    <h2>@Html.DisplayFor(model => model.patient.Nombre) @Html.DisplayFor(model => model.patient.Apellido)</h2>
</div>
<div id="detailInformacion">
    @Html.Label("Información")
</div>
@*        <div id="detailEdit">
        @Html.ActionLink("Editar", "Edit", new { id = Model.Id })
    </div>*@
<section id="detailForm">
    <fieldset>
        <legend>PatientModel</legend>

        <div class="display-label">
            <p><b>@Html.DisplayName("Cedula:")</b> @Html.DisplayFor(model => model.patient.Cedula)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("Fecha de nacimiento:")</b> @Html.DisplayFor(model => model.patient.FechaNacimiento)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("Edad:")</b> @Html.DisplayFor(model => model.patient.Edad)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("Sexo:")</b> @Html.DisplayFor(model => model.patient.Sexo)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("Tipo de Sangre:")</b> @Html.DisplayFor(model => model.patient.TipoSangre)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("Seguro Medico:")</b> @Html.DisplayFor(model => model.patient.SeguroMedico)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("Afiliado No").:</b> @Html.DisplayFor(model => model.patient.NumeroSeguroMedico)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("NSS:")</b> @Html.DisplayFor(model => model.patient.NumeroSeguroSocial)</p>
        </div>

        <div class="display-label">
            <p><b>@Html.DisplayName("Religión:")</b> @Html.DisplayFor(model => model.patient.Religion)</p>
        </div>


        <text>@Html.DisplayName("Creado/Modificado por:") @Html.DisplayFor(model => model.patient.CreadoPor)</text>

        (@Html.ActionLink("Editar", "Edit", new { id = Model.patient.Id }))

    </fieldset>
</section>

<div id="detailBannerForm">
    @Html.Label("Formularios medicos")
</div>
<section id="detailInfoForm" style="padding-left:25px">
    <fieldset>
        <legend>Formularios</legend>
        <div>
            <img src="~/Images/blood pressure.png" width="22" height="22" />@Html.ActionLink("Presión Sanguinea", "Create", "FormBlood", new { id = Model.patient.Id }, null)
        </div>
        <div>
            <img src="~/Images/heart.png" width="22" height="22" />@Html.ActionLink("Signos Vitales", "Create", "VitalSign", new { id = Model.patient.Id }, null)
        </div>
        <div>
            <img src="~/Images/syringe.png" width="22" height="22" />@Html.ActionLink("Vacunas", "Create", "FormVaccination", new { id = Model.patient.Id }, null)
        </div>
        @*<div>
            <img src="~/Images/iv bag.png" width="22" height="22" />@Html.ActionLink("Medicamentos", "SearchPatients", "Patients")
        </div>
        <div>
            <img src="~/Images/bone.png" width="22" height="22" />@Html.ActionLink("Fracturas", "SearchPatients", "Patients")
        </div>
        <div>
            <img src="~/Images/surgeon.png" width="22" height="22" />@Html.ActionLink("Cirugias", "SearchPatients", "Patients")*@
        </div>
        <div>
            @Html.ActionLink("Documentos", "Create", "UploadPhotos", new { id = Model.patient.Id }, null)
        </div>


    </fieldset>
</section>
@*    <nav>
        <section id="menuForm">

            @Ajax.ActionLink("Presión Sanguinea", "_FormPresionSanguinea", "Patients", new {id=Model.Id}, null, new AjaxOptions { UpdateTargetId = "DisplayPartialView" })

            <img src="~/Images/blood pressure.png" width="15" height="15" />@Html.ActionLink("Presión Sanguinea","FormPresionSanguinea", "Patients", new {id=Model.Id}, null) |
            <img src="~/Images/heart.png" width="15" height="15" />@Html.ActionLink("Signos Vitales", "FormSignosVitales", "Patients", new {id=Model.Id},null) |
            <img src="~/Images/virus.png" width="15" height="15" />@Html.ActionLink("Control de Virus", "Create", "Patients") |
            <img src="~/Images/bone.png" width="15" height="15" />@Html.ActionLink("Fracturas", "Formularios", "Patients") |
            <img src="~/Images/surgeon.png" width="15" height="15" />@Html.ActionLink("Cirugias", "Formularios", "Patients") |
            <img src="~/Images/iv bag.png" width="15" height="15" />@Html.ActionLink("Medicamentos", "Formularios", "Patients") 
        </section>
    </nav>*@
<section id="Formularios" style="position:absolute;float:right; width:55%;top: 126px;right:10%">
    <div id="DisplayPartialViewUno" style="border-radius:4px">
        @Html.Action("FormPresionSanguinea", "Patients")
    </div>

    <div id="DisplayPartialViewDos" style="border-radius:4px">
        @Html.Action("FormSignosVitales", "Patients")
    </div>

    <div id="DisplayPartialViewTres" style="border-radius:4px">
        @Html.Action("FormVacunas", "Patients")
    </div>

    <div id="DisplayPartialViewCuatro" style="border-radius:4px">
        @Html.Action("Upload", "Patients")
    </div>
    
    <div id="DisplayPartialViewCuatro" style="border-radius:4px">

        <div id="detailFormName">
            @Html.Label("Historial de Vacunas")
        </div>
        @*<p>
                @Html.ActionLink("Nueva entrada", "Create", "FormBlood")
            </p>*@
        <table>
            <tr>
                <th>
                    @Html.Label("Fecha")
                </th>
                <th>
                    @Html.Label("Paciente")
                </th>
                <th>
                    @Html.Label("Responsable")
                </th>
                <th>
                    @Html.Label("Edad")
                </th>
                <th>
                    @Html.Label("Sexo")
                </th>
                <th>
                    @Html.Label("Alergias")
                </th>
                <th>
                    @Html.Label("Nivel 1")
                </th>
                <th>
                    @Html.Label("Posición 1")
                </th>
                <th>
                    @Html.Label("Nivel 2")
                </th>
                <th>
                    @Html.Label("Posición 2")
                </th>
                <th>
                    @Html.Label("Nivel 3")
                </th>
                <th>
                    @Html.Label("Posición 3")
                </th>
            </tr>

            @foreach (RootObject item in Model.rootObject)
            {
                <tr>
                    <td>
                        @item.modeloDatos.Fecha.dayOfMonth/@item.modeloDatos.Fecha.month/@item.modeloDatos.Fecha.year @item.modeloDatos.Fecha.hourOfDay:@item.modeloDatos.Fecha.minute:@item.modeloDatos.Fecha.second
                    </td>
                    <td>
                        @item.modeloDatos.NombrePaciente
                    </td>
                    <td>
                        @item.modeloDatos.NombreResponsable
                    </td>
                    <td>
                        @item.modeloDatos.Edad
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.modeloDatos.Sexo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.modeloMotivos.Alergias)
                    </td>
                    @foreach (var trauma in item.modeloTrauma)
                    {
                        <td>
                            @Html.DisplayFor(modelItem => trauma.Nivel)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => trauma.Posicion)
                        </td>
                    }

                    @*        <td>
                            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                            @Html.ActionLink("Details", "Details", new { id=item.id }) |
                            @Html.ActionLink("Delete", "Delete", new { id=item.id })
                        </td>*@
                </tr>
            }

        </table>

    </div>

</section>

<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>

ProyectoFinal/Views/Patients/FormPresionSanguinea.cshtml
@model IEnumerable<ProyectoFinal.Models.FormBloodPressure>

@{
    ViewBag.Title = "Historial de Presión Sanguinea";
}
<div id="detailFormName">
@Html.Label("Historial de Presión Sanguinea")
</div>
@*<p>
    @Html.ActionLink("Nueva entrada", "Create", "FormBlood")
</p>*@
<table>
    <tr>
        <th>
            <img src="~/Images/blood pressure.png" width="18" height="18" />
        </th>
        <th>
            @Html.Label("Creado por")
        </th>
        <th>
            @Html.Label("Fecha")
        </th>
        <th>
            @Html.Label("Sistólica")
        </th>
        <th>
            @Html.Label("Diastólica")
        </th>
        <th>
            @Html.Label("Ritmo Cardíaco")
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) 
{
    <tr>
        <td>
            @Html.ActionLink("Editar", "Edit", "FormBlood", new { id=item.Id },null)
            @*@Html.ActionLink("Eliminar", "Delete", "FormBlood", new { id=item.Id },null)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreadoPor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.Sistolica) mmHg</text>
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.Diastolica) mmHg</text>
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.RitmoCardiaco) bpm</text>
        </td>
    </tr>
}
</table>

ProyectoFinal/Views/Patients/FormSignosVitales.cshtml
@model IEnumerable<ProyectoFinal.Models.FormVitalSigns>

@{
    ViewBag.Title = "Historial de Signos Vitales";
}
<div id="detailFormName">
@Html.Label("Historial de Signos Vitales")
</div>
@*<p>
    @Html.ActionLink("Nueva entrada", "Create", "VitalSign")
</p>*@
<table>
    <tr>
        <th>
            <img src="~/Images/heart.png" width="18" height="18" />
        </th>
        <th>
            @Html.Label("Creado por")
        </th>
        <th>
            @Html.Label("Fecha")
        </th>
        <th>
            @Html.Label("Peso")
        </th>
        <th>
            @Html.Label("Temperatura")
        </th>
        <th>
            @Html.Label("Pulso")
        </th>
        <th>
            @Html.Label("PAS/PAD")
        </th>
        <th>
            @Html.Label("FR")
        </th>
        <th>
            @Html.Label("Dolor")
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Editar", "Edit", "VitalSign", new { id=item.Id },null)
            @*@Html.ActionLink("Eliminar", "Delete", "VitalSign", new { id=item.Id },null)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreadoPor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
           <text>@Html.DisplayFor(modelItem => item.Peso) lb.</text>
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.Temperatura) &deg;C</text>
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.Pulso) bpm</text>
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.PresionSanguinea) mmHg</text>
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.Respiracion) bpm</text>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dolor)
        </td>        
    </tr>
}

</table>

ProyectoFinal/Views/Patients/Upload.cshtml
@model IEnumerable<ProyectoFinal.Models.Image>

@{
    ViewBag.Title = "Documentos";
}
<div id="detailFormName">
@Html.Label("Documentos")
</div>
<table>
    <tr>
        <th>
            @Html.Label("Creado por")
        </th>
        <th>
            @Html.Label("Image Path")
        </th>
    </tr>

@foreach (var item in Model) 
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreadoPor)
        </td>
        <td>
            <text>@Html.DisplayFor(modelItem => item.ImagePath)</text>
        </td>
    </tr>
}
</table>